<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Vehicle;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehicles = [
            [
                'name' => 'Toyota Hiace Van',
                'registration_number' => 'WP-ABC-1234',
                'type' => 'van',
                'pax_count' => 12,
                'passenger_count' => 0,
                'price_first_km' => 500.00,
                'price_per_100m_after' => 50.00,
                'available_locations' => ['Colombo', 'Kandy', 'Galle', 'Negombo'],
                'driver_name' => 'Kamal Perera',
                'driver_phone' => '+94771234567',
                'driver_license_number' => 'DL123456789',
                'manufacturing_year' => 2020,
                'brand' => 'Toyota',
                'model' => 'Hiace',
                'color' => 'White',
                'fuel_type' => 'diesel',
                'fuel_capacity' => 70.00,
                'mileage' => 12.5,
                'features' => ['Air Conditioning', 'GPS Navigation', 'Bluetooth'],
                'amenities' => ['Water Bottles', 'Tissues', 'First Aid Kit'],
                'description' => 'Comfortable van perfect for group tours with excellent fuel efficiency.',
                'status' => 'available',
                'is_active' => true,
                'insurance_amount' => 150000.00,
                'insurance_expiry_date' => '2024-12-31',
                'last_maintenance_cost' => 25000.00,
                'last_maintenance_date' => '2024-09-15',
                'next_maintenance_date' => '2025-03-15',
                'admin_notes' => 'Regular maintenance schedule followed.',
            ],
            [
                'name' => 'Honda Civic Car',
                'registration_number' => 'WP-XYZ-5678',
                'type' => 'car',
                'pax_count' => 4,
                'passenger_count' => 0,
                'price_first_km' => 300.00,
                'price_per_100m_after' => 30.00,
                'available_locations' => ['Colombo', 'Kandy', 'Galle'],
                'driver_name' => 'Nimal Silva',
                'driver_phone' => '+94771234568',
                'driver_license_number' => 'DL123456790',
                'manufacturing_year' => 2021,
                'brand' => 'Honda',
                'model' => 'Civic',
                'color' => 'Silver',
                'fuel_type' => 'petrol',
                'fuel_capacity' => 50.00,
                'mileage' => 15.0,
                'features' => ['Air Conditioning', 'Bluetooth', 'USB Charging'],
                'amenities' => ['Water Bottles', 'Phone Charger'],
                'description' => 'Compact and fuel-efficient car ideal for city tours.',
                'status' => 'available',
                'is_active' => true,
                'insurance_amount' => 120000.00,
                'insurance_expiry_date' => '2024-11-30',
                'last_maintenance_cost' => 15000.00,
                'last_maintenance_date' => '2024-08-20',
                'next_maintenance_date' => '2025-02-20',
                'admin_notes' => 'Excellent condition, recently serviced.',
            ],
            [
                'name' => 'Mahindra Bolero Jeep',
                'registration_number' => 'WP-DEF-9012',
                'type' => 'jeep',
                'pax_count' => 8,
                'passenger_count' => 0,
                'price_first_km' => 600.00,
                'price_per_100m_after' => 60.00,
                'available_locations' => ['Colombo', 'Kandy', 'Ella', 'Nuwara Eliya'],
                'driver_name' => 'Sunil Fernando',
                'driver_phone' => '+94771234569',
                'driver_license_number' => 'DL123456791',
                'manufacturing_year' => 2019,
                'brand' => 'Mahindra',
                'model' => 'Bolero',
                'color' => 'Red',
                'fuel_type' => 'diesel',
                'fuel_capacity' => 60.00,
                'mileage' => 10.0,
                'features' => ['Air Conditioning', 'GPS Navigation'],
                'amenities' => ['Water Bottles', 'First Aid Kit', 'Cooler Box'],
                'description' => 'Rugged jeep perfect for hill country and adventure tours.',
                'status' => 'available',
                'is_active' => true,
                'insurance_amount' => 180000.00,
                'insurance_expiry_date' => '2025-01-15',
                'last_maintenance_cost' => 30000.00,
                'last_maintenance_date' => '2024-07-10',
                'next_maintenance_date' => '2025-01-10',
                'admin_notes' => 'Suitable for off-road adventures.',
            ],
            [
                'name' => 'Tata Ace Lorry',
                'registration_number' => 'WP-GHI-3456',
                'type' => 'lorry',
                'pax_count' => 3,
                'passenger_count' => 0,
                'price_first_km' => 400.00,
                'price_per_100m_after' => 40.00,
                'available_locations' => ['Colombo', 'Negombo', 'Chilaw'],
                'driver_name' => 'Ravi Jayasuriya',
                'driver_phone' => '+94771234570',
                'driver_license_number' => 'DL123456792',
                'manufacturing_year' => 2018,
                'brand' => 'Tata',
                'model' => 'Ace',
                'color' => 'Blue',
                'fuel_type' => 'diesel',
                'fuel_capacity' => 45.00,
                'mileage' => 8.5,
                'features' => ['Air Conditioning'],
                'amenities' => ['Water Bottles'],
                'description' => 'Small lorry suitable for cargo transport and small group transfers.',
                'status' => 'maintenance',
                'is_active' => true,
                'insurance_amount' => 100000.00,
                'insurance_expiry_date' => '2024-10-30',
                'last_maintenance_cost' => 20000.00,
                'last_maintenance_date' => '2024-09-01',
                'next_maintenance_date' => '2024-10-01',
                'admin_notes' => 'Currently under maintenance.',
            ],
            [
                'name' => 'Bajaj Tuk Tuk',
                'registration_number' => 'WP-JKL-7890',
                'type' => 'tuk_tuk',
                'pax_count' => 3,
                'passenger_count' => 0,
                'price_first_km' => 200.00,
                'price_per_100m_after' => 20.00,
                'available_locations' => ['Colombo', 'Negombo'],
                'driver_name' => 'Priyantha Kumara',
                'driver_phone' => '+94771234571',
                'driver_license_number' => 'DL123456793',
                'manufacturing_year' => 2022,
                'brand' => 'Bajaj',
                'model' => 'RE',
                'color' => 'Yellow',
                'fuel_type' => 'petrol',
                'fuel_capacity' => 8.00,
                'mileage' => 25.0,
                'features' => [],
                'amenities' => ['Water Bottles'],
                'description' => 'Traditional tuk tuk for short city tours and transfers.',
                'status' => 'available',
                'is_active' => true,
                'insurance_amount' => 50000.00,
                'insurance_expiry_date' => '2024-12-15',
                'last_maintenance_cost' => 5000.00,
                'last_maintenance_date' => '2024-08-15',
                'next_maintenance_date' => '2025-02-15',
                'admin_notes' => 'Popular choice for city tours.',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::create($vehicle);
        }
    }
}